version: '3'
services:
  postgres:
    image: postgres:16-alpine
    container_name: rent-postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

  rentservice:
    image: acmesky-rentservice
    container_name: rent-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./:/etc/data
    restart: unless-stopped

volumes:
  postgres-data:
