version: '3'
services:
  postgres:
    image: postgres:16-alpine
    container_name: rent-postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d
    networks:
      - default

  rentservice:
    image: acmesky-rentservice
    container_name: rent-api
    networks:
      - default
      - acmesky
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./:/etc/data
    restart: unless-stopped

  leonardoservice:
    image: acmesky-rentleonardo
    container_name: rent-leonardo
    networks:
      - acmesky
    ports:
      - "8081:8081"
    volumes:
      - ./:/etc/data
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  acmesky:
    external: true
